default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: roborregos_dashboard_development

test:
  <<: *default
  database: roborregos_dashboard_test

production:
  <<: *default
  database: roborregos_dashboard_development
#  url: <%= ENV['DATABASE_URL'] %>
